import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import { ThemeProvider } from './provider/ThemeProvider';
import Container from '@/components/global/Container';
import { SidebarProvider } from './provider/SidebarProvider';
import Sidebar from '@/components/navbar/Sidebar';
import { BackgroundEffects } from '@/components/global/BackgroundEffects';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <Sidebar />
            <Navbar />
            <BackgroundEffects />
            {/* </BackgroundEffects> */}
            <Container>{children}</Container>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
